apiVersion: v1
kind: Service
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: zomato
  type: LoadBalancer
